# -*- coding: utf-8 -*-
"""realtime traffic counter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E81yyhzXdXTYfCvuxaN7E_jkjJ2qbxF4
"""

pip install ultralytics

!unzip /content/drive/MyDrive/realtime_trafficounter/rtc2dataset.zip -d /content/dataset

from google.colab import drive
drive.mount('/content/drive')

# Di dalam sel Google Colab Anda
from ultralytics import YOLO

# Muat model pre-trained (yolov8s.pt sedikit lebih akurat dari yolov8n.pt)
model = YOLO('yolov8s.pt')

# Jalankan training dengan konfigurasi optimal
results = model.train(
   data='/content/dataset/data.yaml',  # Path ke file data.yaml Anda
   epochs=150,                           # Jumlah epoch yang baik untuk model final
   imgsz=640,                            # Ukuran gambar input standar
   batch=16,                             # Batch size, sesuaikan jika GPU Colab Anda kuat
   project='/content/drive/MyDrive/realtime_trafficounter/YOLOv8_Training', # Lokasi penyimpanan hasil
   name='traffic_counter_final_run'      # Nama folder untuk sesi training ini
)

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/realtime_trafficounter/YOLOv8_Training/traffic_counter_final_run3/weights/last.pt')

results = model.train(resume=True)

import torch
if torch.cuda.is_available():
    print(f"GPU terdeteksi! Nama GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU TIDAK terdeteksi oleh PyTorch.")

